      SUBROUTINE UNBLNK (RECORD,IRLEN)
C----------
C  **UNBLNK--BASE   DATE OF LAST REVISION:  02/16/16
C----------
C
C     THIS SUBROUTINE REMOVES ALL BLANKS FROM A CHARACTER
C     STRING, LEAVING THE NONBLANK CONTENTS OF THE STRING
C     LEFT JUSTIFIED, AND THE REST OF THE STRING BLANK.
C     IRLEN IS RETURNED AS THE LENGTH OF THE NONBLANK PORTION.
C     --- disable to allow filenames with embedded blanks ---
C
      CHARACTER*(*) RECORD
      IRLEN=0
      LENREC=LEN(RECORD)
      DO I=1,LENREC
c         IF (RECORD(I:I).NE.' ') THEN
            IRLEN=IRLEN+1
            IF (IRLEN.LT.I) RECORD(IRLEN:IRLEN)=RECORD(I:I)
c         ENDIF
      ENDDO
      IF (IRLEN.LT.LENREC) RECORD(IRLEN+1:LENREC)=' '
      RETURN
      END
