      SUBROUTINE EXCLIM
      IMPLICIT NONE
C----------
C  $Id$
C----------
C
C     EXTRA EXTERNAL REFERENCES FOR CLIMATE EXTENSION CALLS
C
COMMONS
C
      INCLUDE 'PRGPRM.F77'
C
COMMONS
C
      LOGICAL DEBUG,LKECHO,L
      INTEGER KEY,IRECNT,IPNT,ILIMIT
      CHARACTER*8 KEYWRD,NOCLIM 
      REAL SDIDEF(MAXSP),XMAX,TREEMULT(MAXTRE),WK3(MAXTRE)
C
      DATA NOCLIM/'*NO CLIM'/
C      ENTRY CLINIT
C      RETURN
C      ENTRY CLACTV (L)
C      L=.FALSE.
C      RETURN
C      ENTRY CLSETACTV (L)
C      RETURN
C      ENTRY CLPUT (WK3,IPNT,ILIMIT)
C      RETURN
C      ENTRY CLGET (WK3,IPNT,ILIMIT)
C      RETURN
C      ENTRY CLIN  (DEBUG,LKECHO)
C      CALL ERRGRO (.TRUE.,11)
C      RETURN
      ENTRY CLKEY(KEY,KEYWRD)
      KEYWRD=NOCLIM 
      RETURN
C      ENTRY CLGMULT(TREEMULT)
C      TREEMULT=1.
C      RETURN
C      ENTRY CLMORTS 
C      RETURN
C      ENTRY CLMAXDEN (SDIDEF,XMAX)
C      RETURN 
      ENTRY CLAUESTB
      RETURN 
      END
